## Q7

In [2]:
import pandas as pd
import numpy as np

ames = pd.read_csv("./data/ames_prices.csv")
ames["Central.Air"] = ames["Central.Air"].map({"Y": 1, "N": 0})
ames.columns

Index(['Order', 'PID', 'area', 'price', 'MS.SubClass', 'MS.Zoning',
       'Lot.Frontage', 'Lot.Area', 'Street', 'Alley', 'Lot.Shape',
       'Land.Contour', 'Utilities', 'Lot.Config', 'Land.Slope', 'Neighborhood',
       'Condition.1', 'Condition.2', 'Bldg.Type', 'House.Style',
       'Overall.Qual', 'Overall.Cond', 'Year.Built', 'Year.Remod.Add',
       'Roof.Style', 'Roof.Matl', 'Exterior.1st', 'Exterior.2nd',
       'Mas.Vnr.Type', 'Mas.Vnr.Area', 'Exter.Qual', 'Exter.Cond',
       'Foundation', 'Bsmt.Qual', 'Bsmt.Cond', 'Bsmt.Exposure',
       'BsmtFin.Type.1', 'BsmtFin.SF.1', 'BsmtFin.Type.2', 'BsmtFin.SF.2',
       'Bsmt.Unf.SF', 'Total.Bsmt.SF', 'Heating', 'Heating.QC', 'Central.Air',
       'Electrical', 'X1st.Flr.SF', 'X2nd.Flr.SF', 'Low.Qual.Fin.SF',
       'Bsmt.Full.Bath', 'Bsmt.Half.Bath', 'Full.Bath', 'Half.Bath',
       'Bedroom.AbvGr', 'Kitchen.AbvGr', 'Kitchen.Qual', 'TotRms.AbvGrd',
       'Functional', 'Fireplaces', 'Fireplace.Qu', 'Garage.Type',
       'Garage.Yr.Blt', 'Garage.Finish', 'Garage.Cars', 'Garage.Area',
       'Garage.Qual', 'Garage.Cond', 'Paved.Drive', 'Wood.Deck.SF',
       'Open.Porch.SF', 'Enclosed.Porch', 'X3Ssn.Porch', 'Screen.Porch',
       'Pool.Area', 'Pool.QC', 'Fence', 'Misc.Feature', 'Misc.Val', 'Mo.Sold',
       'Yr.Sold', 'Sale.Type', 'Sale.Condition'],
      dtype='str')

In [3]:
ames["Central.Air"].mean()

np.float64(0.9331058020477816)

a. The proportion of homes in this dataset with central air appears to be around 93.3%.

In [4]:
# b.

import random
random.seed(123)

means = []
B = 2000

for i in range(0,B):
    sample = ames.sample(n=100, replace=True)
    means.append(sample["Central.Air"].mean())

sum(means)/len(means)

np.float64(0.932700000000027)

In [5]:
# c.

std_error = np.std(means, ddof=1)
std_error

np.float64(0.025020451864539772)

In [6]:
# d.

p_hat = ames["Central.Air"].mean()

critical_values = {
    "90%": 1.645,
    "95%": 1.960,
    "99%": 2.576
}

for level, z in critical_values.items():
    lower = p_hat - z * std_error
    upper = p_hat + z * std_error
    print(f"{level} confidence interval: ({lower:.4f}, {upper:.4f})")

90% confidence interval: (0.8919, 0.9743)
95% confidence interval: (0.8841, 0.9821)
99% confidence interval: (0.8687, 0.9976)

e. For null hypothesis Ho: p = .9, we fail to reject the null hypothesis at .1, .05, and .01 significance levels since .9 falls within the confidence interval for the 90%, 95% and 99% confidence interval. For interpretation, we are 95% confident the true proprotion of home with central air in ames is between roughly .8835 and .9827.

## Q8

In [7]:
# a.

random.seed(456)

p_hat = np.arcsinh(ames["area"]).corr(np.arcsinh(ames["price"]))

B = 2000
corrs = []

for i in range(0,B):
    sample = ames.sample(n=100, replace=True)
    corr = np.arcsinh(sample["area"]).corr(np.arcsinh(sample["price"]))
    corrs.append(corr)

sum(corrs)/len(corrs)

np.float64(0.7223542113929824)

In [8]:
# b.

std_error2 = np.std(corrs, ddof=1)
std_error2

np.float64(0.05559266118623149)

In [9]:
# c.

critical_values = {
    "90%": 1.645,
    "95%": 1.960,
    "99%": 2.576
}

for level, z in critical_values.items():
    lower = p_hat - z * std_error2
    upper = p_hat + z * std_error2
    print(f"{level} confidence interval: ({lower:.4f}, {upper:.4f})")

90% confidence interval: (0.6317, 0.8146)
95% confidence interval: (0.6142, 0.8321)
99% confidence interval: (0.5800, 0.8664)

d. For significance levels .1, .05, and .01, we will reject the null hypothesis Ho: p=0 as 0 is excluded from the 90%, 95%, and 99% confidence interval suggesting that there is sufficient evidence to conclude that there is a noticable correlation between area and price of a home. 

e. Area and price must remain paired during resampling since each observation represents one home's area and its corresponding price. Resampling the two variables independently would break these pairings and distort the relationship, producing an inaccurate estimate of the correlation.

## Q9

In [10]:
meta = pd.read_csv("./data/metabric.csv")
meta.head()

,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Chemotherapy,Hormone Therapy,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Overall Survival Status,Radio Therapy,TMB (nonsynonymous),Tumor Size,Tumor Stage
0,43.19,BREAST CONSERVING,Breast Cancer,NO,YES,0.0,2.0,4.020,84.633333,0:LIVING,YES,2.615035,10.0,1.0
1,48.87,MASTECTOMY,Breast Cancer,YES,YES,1.0,2.0,4.030,163.700000,1:DECEASED,NO,2.615035,15.0,2.0
2,47.68,MASTECTOMY,Breast Cancer,YES,YES,3.0,1.0,4.050,164.933333,0:LIVING,YES,1.307518,25.0,2.0
3,76.97,MASTECTOMY,Breast Cancer,YES,YES,8.0,2.0,6.080,41.366667,1:DECEASED,YES,2.615035,40.0,2.0
4,78.77,MASTECTOMY,Breast Cancer,NO,YES,0.0,4.0,4.062,7.800000,1:DECEASED,YES,5.230071,31.0,4.0

In [11]:
# a.

random.seed(789)

x_bar = meta["Overall Survival (Months)"].mean()

means2 = []
B = 2000

for i in range(0,B):
    sample = meta.sample(n=100, replace=True)
    means2.append(sample["Overall Survival (Months)"].mean())

sum(means2)/len(means2)

np.float64(128.8276521666668)

In [12]:
# b.

std_error3 = np.std(means2, ddof=1)
std_error3

np.float64(7.766718942332577)

In [13]:
# c.

critical_values = {
    "90%": 1.645,
    "95%": 1.960,
    "99%": 2.576
}

for level, z in critical_values.items():
    lower = x_bar - z * std_error3
    upper = x_bar + z * std_error3
    print(f"{level} confidence interval: ({lower:.4f}, {upper:.4f})")

90% confidence interval: (116.3180, 141.8705)
95% confidence interval: (113.8715, 144.3171)
99% confidence interval: (109.0872, 149.1014)

d. For significance levels .1, .05, and .01, we will fail to reject the null hypothesis Ho: m=120 as 120 is included from the 90%, 95%, and 99% confidence interval suggesting that there is not sufficient evidence to conclude that mean overall survival months is not 120. 

e. 
- The estimated mean surival time is about 129.0943 months, or about 10.76 years.
- 90% confidence interval: average survival is 116.3841–141.8045 months, or approximately 9.7–11.82 years
- 95% confidence interval: average survival is 113.9502–144.2384 months, or approximately 9.5–12.02 years
- 99% confidence interval: average survival is 109.1906–148.9979 months, or approximately 9.1–12.42 years

Because some patients are still alive at the end of the study, their eventual death times are right-censored (we know they survived at least until their last observation, but do not represent their total lifetimes). Treating these observed times as completed lifetimes would underestimate mean survival time. Therefore, these estimates do not necessarily represent the true population mean survival time.

## Q10

In [14]:
nhanes = pd.read_csv("./data/nhanes_data_17_18.csv")
nhanes = nhanes[nhanes["AgeInYearsAtScreening"]>18]
nhanes = nhanes[nhanes["SleepHoursWeekdaysOrWorkdays"].notnull()]
nhanes.head()

C:\Users\jjsut\AppData\Local\Temp\ipykernel_17456\4282670806.py:1: DtypeWarning: Columns (0: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes = pd.read_csv("./data/nhanes_data_17_18.csv")

,SEQN,GeneralHealthCondition,EverBreastfedOrFedBreastmilk,AgeStoppedBreastfeedingdays,AgeFirstFedFormuladays,AgeStoppedReceivingFormuladays,AgeStartedOtherFoodbeverage,AgeFirstFedMilkdays,TypeOfMilkFirstFedWholeMilk,TypeOfMilkFirstFed2Milk,...,DaysSmokedCigsDuringPast30Days,AvgCigarettesdayDuringPast30Days,TriedToQuitSmoking,TimesStoppedSmokingCigarettes,HowLongWereYouAbleToStopSmoking,UnitOfMeasureDayweekmonthyear_2_SMQ,CurrentSelfreportedHeightInches,CurrentSelfreportedWeightPounds,TriedToLoseWeightInPastYear,TimesLost10LbsOrMoreToLoseWeight
2,93705.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,165.0,0.0,11 times or more
5,93708.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,118.0,0.0,Never
6,93709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,5.0,0.0,NaN,NaN,NaN,62.0,200.0,0.0,6 to 10
7,93711.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,69.0,142.0,0.0,Never
9,93713.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,15.0,1.0,3.0,1.0,Days,70.0,165.0,0.0,Never

In [15]:
# a.

random.seed(123456789)

x_bar2 = nhanes["SleepHoursWeekdaysOrWorkdays"].mean()

B = 2000
means3 = []

for i in range(0,B):
    sample = nhanes.sample(n=100, replace=True)
    means3.append(sample["SleepHoursWeekdaysOrWorkdays"].mean())

sum(means3)/len(means3)

np.float64(7.600677499999996)

In [16]:
# b.

std_error4 = np.std(means3, ddof=1)
std_error4

np.float64(0.16393913966624094)

In [17]:
# c.

critical_values = {
    "90%": 1.645,
    "95%": 1.960,
    "99%": 2.576
}

for level, z in critical_values.items():
    lower = x_bar2 - z * std_error4
    upper = x_bar2 + z * std_error4
    print(f"{level} confidence interval: ({lower:.4f}, {upper:.4f})")

90% confidence interval: (7.3358, 7.8752)
95% confidence interval: (7.2842, 7.9268)
99% confidence interval: (7.1832, 8.0278)

d. At significance levels .1 and .05, we reject the null hypothesis Ho: m=8 (hours of sleep) since the 90% and 95% confidence intervals do not include 8, but at significance level .01, we fail to reject the null hypothesis since 8 is contained in the 99% confidence interval.

e. The estimated mean amount of sleep is around 7.6055 hours, which is about 24 minutes less than the null hypothesis 8 hours. Statistical and practical significance do not necessarily tell the same story. Although the difference of approximately 24 minutes is statistically significant at the .1 and .05 levels, whether it is practically important depends on the context, such as the effects of this difference on health, concentration, daily functioning, etc.. A difference of 24 minutes may be meaningful in some cases, but statistical significance alone does not establish that the difference has meaningful impact in the real world.